name: Reusable workflow
on:
  workflow_call:
    inputs:
      name: 
        description: Enter the name
        required: true
        type: string

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting step
        run: echo "${{inputs.name}}Welcome to reusable workflow"

